# (PART) Specific Topics {-}

# Introduction

This part of the book provides tutorials on specific topics using R. These tutorials are written and curated by scholarship participants. 

## Contributors

### Afton - [Map Visualizations](#topics-map-viz)

>My name is Afton and I work as a statistical programmer for Murphy Research, a market research company  based in Los Angeles. My background is originally in linguistics, and I graduated with an MA in linguistics from the University of Southern California. Connect with me on [Twitter](https://twitter.com/aftonsteps) or [LinkedIn](https://www.linkedin.com/in/aftoncoombs) so we can talk more about data and language!

### Jolynn - [Udacity Even Lessons](#topics-lessons)

>My name is Jolynn. I am a spatial data analyst with a masters in GIS from Penn State, where I studied remote sensing and spatial statistics. You can see some of my maps on my [website]( https://jolynns1.wixsite.com/mgis) or find me on [LinkedIn]( https://www.linkedin.com/in/jolynnschmidt/).

### Josh - [Basic dplyr](#topics-sql-dplyr)

>My name is Josh and I currently work as the Manager of Data Analysis for [AACSB International](https://www.aacsb.edu/). I hold an MA in Economics from the University of South Florida (Go Bulls!), and have a background in Statistics as well. Examples of my work include a [shinydashboard](https://aacsb.shinyapps.io/DataDashboard/), a [blog post written in R Markdown](http://aacsbblogs.typepad.com/dataandresearch/2018/05/aacsb-and-aaup-faculty-salary-comparative-analysis-.html) and [a publication](https://www.aacsb.edu/-/media/aacsb/publications/data-trends-booklet/aacsb%20data%20guide%202018-a4-final.ashx?la=en) with tables and figures made with the tidyverse. You can follow me on [Twitter](https://twitter.com/jdbarillas) or add me on [LinkedIn](https://www.linkedin.com/in/jdbarillas/).

### How to contribute

We are using a shared repository model. Therefore, you can contribute to the book by following these steps:

1. Clone [the book repo](https://github.com/jdbarillas/r4bdsp) from GitHub.
2. Create a separate branch for your topic
3. Add the file(s) to the proper directories and commit the changes to your topic branch 
4. Push the changes to GitHub and submit a [pull request](https://help.github.com/articles/about-pull-requests/)

For information on the shared repository model, see [here](https://gist.github.com/seshness/3943237) and [here](https://github.com/NuCivic/nucivic-process/wiki/Github-Shared-Repository-Model).